name: Canvas to Website
on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Convert .canvas to HTML
        run: |
          npm install rehype-jsoncanvas
          npx rehype-jsoncanvas "test.canvas" -o dist/index.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
