name: Canvas to Website
on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Test npx  # Keep this for debugging
        run: npx cowsay "Hello from npx"

      - name: Convert .canvas to HTML
        run: |
          set -e
          mkdir -p dist
          npm install rehype-jsoncanvas
          for file in canvases/*.canvas; do
            filename=$(basename "$file")
            filename_no_ext="${filename%.*}"
            ./node_modules/.bin/rehype-jsoncanvas "$file" -o "dist/${filename_no_ext}.html"
          done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
